### ISSUE TITLE
How to run this code?

### ISSUE THREAD

**Issue by machenxiang** [cholazzzb/APF_Swarm_Control_Simulator#1]
Dear Nicholas Biantoro:
        I'm sorry to bother you. I want to ask how to run this code? I can't find the main file. Thanks in advance.

**Comment by cholazzzb** [comment]
Hello, this repo is still under development. For this moment you can run /python_code/Quadrotor/test/testQuadrotor.py or you can run any of main_*.py in /python_code directory
